language: ruby
rvm:
- 2.1.3
env:
  secure: wB72at47hlNQIgZE1bEF8/mrj4i/Ej8sLoO7h/kmV03EGU+HrGKOuKvsy3frl/LrWD0XF4coQwb8sekG5Td8UkgOjNs9PArQF8EoABgcN3kFoGdQAYeIIFgdh50n76TRub6gQiPKi/aZYA1ETC809i2CP2O3hcnxUtPgRMejlZM=
